"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { getTopic, STARTERS } from "@/lib/constants";
import { subjectLabel } from "./subjects";
import { MobileTutorTopicDrawer, TutorTopicSidebar } from "./tutor-topic-sidebar";

interface ConversationViewProps { subjectId: string; level: string; topicId: string; stuck: boolean; onRevealStuck: () => void; onOpenTopic: (topicId: string) => void; }

export function ConversationView({ subjectId, level, topicId, stuck, onRevealStuck, onOpenTopic }: ConversationViewProps) {
  const subject = subjectLabel(subjectId);
  const topic = getTopic(subjectId, topicId);
  const starters = STARTERS[`${subjectId}:${topic.id}`] ?? STARTERS[subjectId] ?? [];
  const [topicsOpen, setTopicsOpen] = useState(false);
  const [draft, setDraft] = useState("");
  const [sessionMessages, setSessionMessages] = useState<string[]>([]);
  const bottomRef = useRef<HTMLDivElement | null>(null);
  const scrollToBottom = useCallback(() => bottomRef.current?.scrollIntoView({ block: "end" }), []);
  useEffect(() => { window.requestAnimationFrame(scrollToBottom); }, [scrollToBottom, sessionMessages.length, stuck, topic.id]);
  const submit = (event: React.FormEvent) => { event.preventDefault(); const message = draft.trim(); if (!message) return; setSessionMessages((current) => [...current, message]); setDraft(""); };

  return <div className="mx-auto grid h-[calc(100dvh-65px)] max-w-[1180px] grid-cols-1 overflow-hidden lg:grid-cols-[260px_minmax(0,1fr)]">
    <TutorTopicSidebar subjectId={subjectId} activeTopicId={topic.id} onSelectTopic={onOpenTopic} />
    <MobileTutorTopicDrawer subjectId={subjectId} activeTopicId={topic.id} open={topicsOpen} onClose={() => setTopicsOpen(false)} onSelectTopic={onOpenTopic} />
    <div className="flex min-h-0 min-w-0 flex-col px-4 sm:px-6"><div className="flex shrink-0 items-center gap-3 border-b border-gray-200 px-1 pb-3 pt-4 dark:border-slate-800"><button type="button" onClick={() => setTopicsOpen(true)} aria-label="Open tutor topics" className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl border border-gray-200 bg-white text-gray-600 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200 lg:hidden">☰</button><span className="relative flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-cyan-500 font-heading text-sm font-semibold text-white">AI</span><div className="min-w-0 flex-1"><div className="font-heading text-[17px] font-semibold text-gray-900 dark:text-white">Subject tutor</div><div className="truncate text-[12.5px] text-gray-400">{subject} / {level === "OL" ? "Ordinary Level" : "Higher Level"} / {topic.name}</div></div><span className="hidden rounded-full border border-gray-200 bg-gray-100 px-3 py-1.5 text-xs text-gray-500 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-300 sm:inline">Socratic mode</span></div>
      <div className="flex min-h-0 flex-1 flex-col gap-4 overflow-y-auto px-1 pb-4 pt-4"><TutorBubble>You&apos;re in {topic.name}. Ask a question from this topic, paste an exam question, or choose one of the starters below. I&apos;ll guide you step by step.</TutorBubble>{starters.length > 0 && <div className="flex flex-wrap gap-2 sm:ml-[41px]">{starters.slice(0, 3).map((starter) => <span key={starter} className="rounded-full border border-cyan-100 bg-white px-3 py-1.5 text-[12.5px] text-gray-600 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200">{starter}</span>)}</div>}<TopicContext topicName={topic.name} /><TutorBubble>Before we solve anything, what feels least clear: the concept, the exam wording, or the first step in a question?</TutorBubble><StudentBubble>I understand it in class, but I&apos;m not sure how to start when it appears in an exam question.</StudentBubble><TutorBubble>Good. What clue in the question tells you this is a {topic.name} problem? Name one, even if you&apos;re not fully sure.</TutorBubble>{stuck && <TutorBubble>Start by listing the information you are given, then underline exactly what the question asks for. That is usually enough to find the first move.</TutorBubble>}{sessionMessages.map((message, index) => <StudentBubble key={`${index}-${message}`}>{message}</StudentBubble>)}<div ref={bottomRef} /></div>
      <div className="shrink-0 border-t border-gray-100 bg-[#f4f8f6]/95 px-1 pb-[calc(1rem+env(safe-area-inset-bottom))] pt-3 backdrop-blur-sm dark:border-slate-800 dark:bg-slate-950/95"><div className="mb-2.5 flex flex-wrap gap-2"><QuickAction onClick={onRevealStuck}>Give me a hint</QuickAction><QuickAction onClick={onRevealStuck}>I&apos;m still stuck</QuickAction><QuickAction>Show a worked example</QuickAction></div><form onSubmit={submit} className="flex items-center gap-2.5 rounded-[13px] border border-gray-200 bg-white py-1.5 pl-4 pr-1.5 shadow-[0_6px_18px_-14px_rgba(17,24,39,.5)] dark:border-slate-700 dark:bg-slate-900"><input value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="Reply to your tutor..." className="flex-1 border-none bg-transparent py-2.5 text-[14.5px] text-gray-700 outline-none dark:text-white" /><button type="submit" disabled={!draft.trim()} aria-label="Send message" className="flex h-[38px] w-[38px] shrink-0 items-center justify-center rounded-[10px] bg-cyan-500 text-white disabled:bg-gray-300">→</button></form><div className="mt-2 text-center text-[11.5px] text-gray-400">Your tutor guides you toward the answer instead of simply giving it away.</div></div>
    </div>
  </div>;
}

function TutorBubble({ children }: { children: React.ReactNode }) { return <div className="flex max-w-[88%] gap-2.5"><span className="flex h-[30px] w-[30px] shrink-0 items-center justify-center rounded-full bg-cyan-500 font-heading text-[11px] font-semibold text-white">AI</span><div className="rounded-b-2xl rounded-tl-sm rounded-tr-2xl bg-gray-100 px-4 py-[13px] text-[14.5px] leading-relaxed text-gray-900 dark:bg-slate-800 dark:text-slate-100">{children}</div></div>; }
function StudentBubble({ children }: { children: React.ReactNode }) { return <div className="flex justify-end"><div className="max-w-[80%] rounded-b-2xl rounded-tl-2xl rounded-tr-sm bg-cyan-500 px-[15px] py-[11px] text-[14.5px] leading-relaxed text-white">{children}</div></div>; }
function QuickAction({ children, onClick }: { children: React.ReactNode; onClick?: () => void }) { return <button type="button" onClick={onClick} className="rounded-full border border-gray-200 bg-white px-3 py-2 text-[12.5px] font-medium text-gray-700 hover:border-cyan-500 hover:text-cyan-700 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200">{children}</button>; }
function TopicContext({ topicName }: { topicName: string }) { return <div className="overflow-hidden rounded-xl border border-gray-200 bg-gray-50 shadow-[0_10px_30px_-24px_rgba(17,24,39,.6)] sm:ml-[41px] dark:border-slate-700 dark:bg-slate-900"><div className="flex items-center gap-2 border-b border-gray-200 bg-gray-100 px-4 py-2.5 text-xs dark:border-slate-700 dark:bg-slate-800"><span className="font-mono font-semibold uppercase tracking-[.06em] text-gray-500">Topic context</span><span className="text-gray-400">Mapped subject context</span></div><div className="px-5 py-4"><p className="m-0 text-[13px] text-gray-500">This session uses the mapped topic context:</p><div className="font-heading py-2 text-center text-xl text-gray-900 dark:text-white">{topicName}</div></div><div className="border-t border-gray-200 px-4 py-2.5 text-xs text-gray-500 dark:border-slate-700">Topic mapping is preserved for subject context and retrieval.</div></div>; }
