-- Document hosted exam_chunks vector RPC for local parity.
-- Hosted project already has this function + ~3k embedded chunks (Maths, English, Biology, Business, Geography).

create extension if not exists vector;

create table if not exists public.exam_chunks (
  id bigint generated by default as identity primary key,
  subject text not null,
  year integer,
  level text,
  paper_num integer,
  question_ref text,
  chunk_index integer,
  content text,
  source_file text,
  source_path text,
  embedding vector(1536),
  created_at timestamptz default now(),
  topic text
);

-- Required for ingest upsert onConflict: source_path,chunk_index
create unique index if not exists exam_chunks_source_chunk_idx
  on public.exam_chunks (source_path, chunk_index);

create index if not exists exam_chunks_subject_idx on public.exam_chunks (subject);
create index if not exists exam_chunks_level_idx on public.exam_chunks (level);
create index if not exists exam_chunks_topic_idx on public.exam_chunks (topic);

create or replace function public.match_exam_chunks(
  query_embedding text,
  match_count integer default 5,
  filter_subject text default null,
  filter_level text default null,
  filter_topic text default null,
  filter_year_min integer default null,
  filter_year_max integer default null
)
returns table (
  id bigint,
  subject text,
  year integer,
  level text,
  paper_num integer,
  topic text,
  question_ref text,
  content text,
  source_file text,
  source_path text,
  similarity double precision
)
language plpgsql
as $$
begin
  return query
  select
    c.id,
    c.subject,
    c.year,
    c.level,
    c.paper_num,
    c.topic,
    c.question_ref,
    c.content,
    c.source_file,
    c.source_path,
    1 - (c.embedding <=> query_embedding::vector) as similarity
  from public.exam_chunks c
  where
    (filter_subject is null or c.subject = filter_subject)
    and (filter_level is null or c.level = filter_level)
    and (filter_topic is null or c.topic = filter_topic)
    and (filter_year_min is null or c.year >= filter_year_min)
    and (filter_year_max is null or c.year <= filter_year_max)
  order by c.embedding <=> query_embedding::vector
  limit match_count;
end;
$$;
